### ISSUE TITLE
Bonznn Be!

### ISSUE THREAD

**Issue by BonziWorldzalt** [endermanch-expose-army/Send-Your-Bytebeat-#9]
[better in 8khz](https://sarpnt.github.io/bytebeat-composer/#v4q1ZKzk9JVbJSSrQ1MTAw0InJS7I10DM0MgWyomPyYkrAREyJhkaJlpGqkampnaGRhaaWhYGmloahLlDQWDVRUz9RUwehzIQ4ZWaElMVGp+Xk5xeBRPUTVY01Y4GicDGgIlXDWKVaAA)

**Comment by G9-Dev-RealIsCool** [comment]
If You Don't Know What Is This. Then I Need To Edit The Issue Name.

**Comment by BonziWorldzalt** [comment]
> If You Don't Know What Is This. Then I Need To Edit The Issue Name.

i just dont know whats this

**Comment by G9-Dev-RealIsCool** [comment]
This is Bonznn Be!

**Comment by BonziWorldzalt** [comment]
ok thanks for the name!

**Comment by G9-Dev-RealIsCool** [comment]
No Problem
